### ISSUE TITLE
AutoMan not terminating

### ISSUE THREAD

**Issue by btamaska** [dbarowy/AutoMan#12]
1. I ran simple_program in AutoMan.
2. Completed one HIT in the worker sandbox. (selected spongebob)
3. Timeout occurred
4. Completed 4 more HITs in the worker sandbox. (selected spongebob each time)
5. AutoMan not terminating even though it now has 5 identical answers. Says it only has 4

**Comment by dbarowy** [comment]
Fixed in commit a4b6d8f968419207c65a29dd239a5515eb8599d7.
