### ISSUE TITLE
simple_program runtime exception

### ISSUE THREAD

**Issue by BartoszJanota** [dbarowy/AutoMan#26]
The exception below occurs always when running simple_program on `pattern_matching` branch.

![image](https://cloud.githubusercontent.com/assets/4175279/8105119/90f043ea-1036-11e5-8536-60c363d998ea.png)

**Comment by dbarowy** [comment]
Commit 0477d6f0c832512a9a1f8ad56fc521d2ff4ed071 fixes exception but introduces a new problem since the scheduler's virtual clock is not incremented correctly.  Will fix tomorrow.

**Comment by dbarowy** [comment]
Fixed with commit ef0bdbb9f4d61513cdc6575a81f7785ac1dc1480.
